### ISSUE TITLE
Something wrong in /F20/

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#100]
`\todo{something is wrong, here}`

Was at /F20/, i removed it cause it disturbed the build process.

**Comment by jGleitz** [comment]
Oh, good you added this issue. Because I removed it in #99, too (but forgot to mention)

**Comment by jGleitz** [comment]
What exactly did the author of this `\todo` try to say?

**Comment by RomanLangrehr** [comment]
I'm not sure, but F20 sounds like we would use multiple measurement tools together.

**Comment by jGleitz** [comment]
> but F20 sounds like we would use multiple measurement tools together.

Well that might be just the case.

> “one or multiple”

**Comment by m1cm1c** [comment]
The sentence didn't make any sense but I didn't know what the author intended to say, so I added a todo.

**Comment by jGleitz** [comment]
It’s by me. Unfortunately I can’t understand what cannot be understood by

> Beagle conducts one or multiple measurement softwares to measure the
sections found in /F10/.

**Comment by jGleitz** [comment]
I means that Beagle will instruct one ore more measurement softwares to measure the sections he likes to have measured. Really can’t think of another wording ;)

**Comment by m1cm1c** [comment]
My guess was that "conduct" was chosen correctly but "software" wasn't. But then again it was written as a part of a explicitly stated compound term, so I was confused. Please replace "conducts" by "employs" or "utilises".

**Comment by jGleitz** [comment]
It’s sad you don’t like the term “conduct”, as from my point of view it exactly expresses what we’ll do

**Comment by flyfl** [comment]
I also like "conduct"

**Comment by m1cm1c** [comment]
You can't "conduct" a software. That's simply not how the word is used. It might be confusing since you can conduct other things that a nouns (like an experiment) but you can't conduct a chair or a software.

**Comment by jGleitz** [comment]
> You can't "conduct" a software.

Yes you can. I just thought of the word to be fitting. But now that I started to read literature, I found that the SDQ seems to agree with me: 

> […] and   measurements   can   be conducted  […]
 [Evaluating Performance of Software Architecture Models with the Palladio Component Model](http://www.palladio-simulator.com/fileadmin/user_upload/palladio-simulator/documents/Introduction-Chapter-PCM.pdf) p. 2

> […] To conduct QoS analyses, component specifications must contain information on how system resources […] are used by components.
[The Palladio Component Model](http://primo.bibliothek.kit.edu/primo_library/libweb/action/dlDisplay.do?vid=KIT&docId=KITSRCE1000022503&tab=kit_evastar&srt=date) p. 58

**Comment by m1cm1c** [comment]
It's used correctly in both cases. You can conduct measurements and you can conduct an analysis. In both cases, an instance only exist when you do something. A software (like a chair) exists even if you don't do anything. (Note that "measurement" is meant as the activity of measuring, not as a result of the process of measuring.)

**Comment by jGleitz** [comment]
Well I’m glad you’re such an expert at the English language. I honestly think you got that wrong, because I don’t why “conducting” implies that the thing did not exists beforehand.

> Both the orchestra and the piece existed before they were conducted. But they were of no use before they were conducted.

> Both the measurement software and the measured software existed before they were conducted. But they were of no use before they were conducted.

I think “to conduct” is a very descriptive word. Because we don’t actually do something, we tell others to do it. Now the important part is that we are *leading* the process. We are not simply *instructing* the software, we are *conducting* numerous measurement runs (like instruments in an orchestra) to bring them together for a greater good.

If you like “to conduct software measurement runs” better because that fits more in your view of that word, we can use that.

**Comment by m1cm1c** [comment]
That's not an actual rule I got from somewhere but it seems to be accurate as I couldn't find any counter examples. I tried to come up with a rule to explain why "conduct" can't be used in that sentence. It means "durchführen", "leiten" (as in conducting electricity, not as in leading something) or "benehmen" when used as a verb. Other translations like "betreiben" simply come from the fact that you can use "betreiben" in German in both cases ("durchführen"). You [won't be able to find anything where "conduct" is used as verb with a static instance afterwards](http://sentence.yourdictionary.com/conduct), though, [nor will you find "conduct" used as a verb with the word "software" afterwards](https://www.google.de/search?client=ubuntu&channel=fs&q=%22conduct+software%22&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=ZLpVVqahDarF8Aex6IO4BA).

**Comment by jGleitz** [comment]
> I couldn't find any counter examples

See above. The orchestra.

> It means "durchführen", "leiten" 

It also means “etw. ausführen”, “etw. verwalten”  and – most importantly – **“etw. dirigieren”** ([source](http://dict.leo.org/ende/index_de.html#/search=conduct&searchLoc=0&resultOrder=basic&multiwordShowSingle=on))

> You won't be able to find anything where "conduct" is used as verb with a static instance afterwards
Yes, I am, I just use another dictionary: [Leo](http://dict.leo.org/ende/index_de.html#/search=conduct&searchLoc=0&resultOrder=basic&multiwordShowSingle=on)

But instead of bashing meaningless arguments in our faces (because be honest, we both just throw in some arguments without having some **real** facts. We just try to strengthen our views, which are based on personal feelings), we should try to come to a conclusion. We’re adults, after all.

@flyfl and me like the image conveyed by “to conduct” , you think one cannot “conduct” software. Would 

> Beagle conducts measurements of the sections found in /F10/ by utilising one or multiple measurement softwares.

Because that’s what I wanted to say in the first place in is more precise anyway. And we already agreed that you can “conduct” measurements.

**Comment by m1cm1c** [comment]
That's great phrasing :). But "by" instead of "in" would be better since these sections are found by a function and "in" is misleading (the reader might expect there to be set sections of which they can find a list in `/F10/`).
