### ISSUE TITLE
Compare the SRS Draft to meeting minutes

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#121]
We had 3 meetings to specify attributes of our software. We should check that everything written in the mettings’ minutes found its ways into the SRS.

**Comment by flyfl** [comment]
I'm not sure what points have been improved the last two hours, please let me know, if I mentioned something redundant.

#Improvements to conform with Meeting Minutes

##Environment
- The dependencies should belong into this section, not into "Non-functional". (We had that discussion quite a time ago)

- In our SPS we talk a lot about the usage of Beagle on servers implicit, but we never mention that Beagle should run on a server explicit.

##Functional requirements
####Mandtatory
- Missing: option to load stored data (states)

####Optional
- Missing: Beagle should analyse source code in one turn (architecture + performance). I think we can skip this point, because we don't want Beagle to depend on a re-engineering tool like Somox. Beagle should only depend on PCM (and CTA for sure).


##Non-functional requirements
####Mandatory
- Missing: Once started with measurements, Beagle runs completely with no need to user interaction.


##Challenges
- We once talked aboud, how to improve measurements to be more objectiv. That included `warming up of CPU (~1 min)` `repeating measurements 20-30 times`. Maybe we could add this points into /C20/, as a possible solution how to deal with this challenging point.

- Missing: The idea of byte counter. Should we skip it? If we want to mention it, I think it fits best into Challenges (as kind of improvement or solution, that is actual also quite effortful).

- Missing: Different software that is running in concurrent on the same device/computer

**Comment by RomanLangrehr** [comment]
> Missing: Beagle should analyse source code in one turn (architecture + performance). I think we can skip this point, because we don't want Beagle to depend on a re-engineering tool like Somox. Beagle should only depend on PCM (and CTA for sure).

I think we can manage this without dependencies to SoMoX: SoMoX offers (or at least will offer) hooks, where Beagle can be started (loose coupling)

**Comment by flyfl** [comment]
As no further comments have been made on my suggestions, I guess we can close this issue?

**Comment by jGleitz** [comment]
I have not yet read through it. I’ll do and then close it accordingly or open a PR.
