### ISSUE TITLE
Model Association Qualifiers in Papyrus

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#263]
I’m unable to do it. I did research, but the explained way does not work for me. Help is highly appreciated.

**Comment by RomanLangrehr** [comment]
![image](https://cloud.githubusercontent.com/assets/10776736/12034599/863408a6-ae33-11e5-8796-799a30d36bb2.png)
That's what you want, isn't it?
Because i think that's not, what we need, as our "qualifier" is not an primitive type.

I think, that's what we need:
![image](https://cloud.githubusercontent.com/assets/10776736/12034623/ed35b0ae-ae33-11e5-9f3e-626ce6ae83f3.png)

**Comment by jGleitz** [comment]
>  That's what you want, isn't it?

Yes it is.

> as our "qualifier" is not an primitive type.

Why should qualifiers always be primitive types? Neither have I heard of that, nor do I think that it would make sense.I think, that's what we need:

> I think, that's what we need:

I’m pretty sure its not. This pattern means that the association itself is *represented* by a class. In our case, we’re want to *partition* the association.

**Comment by jGleitz** [comment]
We found a dirty hack for this in the last session. We now need to apply it.
