### ISSUE TITLE
Protoype for Eclipse GUI

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#275]
We should develop a protoyp which displays a small GUI for our tool.

(This should be displayed later after the "Analyse with Beagle" context menu entry)

**Comment by m1cm1c** [comment]
### What I did

I have created a prototype for the GUI. You can find it in the branch `eclipse-gui-prototype` in my repository.

I searched for hours for a good way to create the GUI. In the end, I reverted back to Swing because other approaches (SWT, different builders, RCP ViewPart, Eclipse 4 ViewPart, XWT Application, JFace Dialog, etc.) didn't work properly or at all. This is ugly and we should create the final GUI in SWT or something else which looks good, even if we don't find a builder. However, Swing will do for a prototype.

My branch builds on top of branch `gui-prototype-test` of @RomanLangrehr, not on top of his branch `gui-prototype`, the reasons for which should be obvious from [this comment](https://github.com/Beagle-PSE/Beagle/pull/281#issuecomment-165936443).

The GUI prototype is integrated into all context menus provided by the current version of @RomanLangrehr's branch `gui-prototype-test`. So far, I didn't remove his pop-ups. The GUI launches after they have been closed.

### Your Help is Needed

We need ideas and suggestions for more GUI features. Please let me know your's so I can improve this provisional prototype.

**Comment by jGleitz** [comment]
Your project requires `miglayout15-swing.jar`, which is neither included, nor defined as dependency in `build.gradle`, nor referenced in `Development Setup.md`. The latest [MiG Layout](http://www.miglayout.com/) release is 4.0.

So how can we try your code?

**Comment by jGleitz** [comment]
Even though I’m unable to try out your branch, I’ll put in my two pennies worth:

Basically, I think that our GUI should use exclusively Eclipse’s features.

> This is ugly and we should create the final GUI in SWT

I don’t think that it matters whether our GUI in “ugly”. But what matters a lot is whether it integrates well into Eclipse.

> even if we don't find a builder

From my point of view, GUI builders are not important at all.

> However, Swing will do for a prototype.

I disagree. From my point of view, this prototype should primary aim to integrate into the Eclipse UI and UX, e.g. by using the features described in the [Eclipse Programmer’s Guide](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Ffirstplugin.htm), like [UI Forms](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Ffirstplugin.htm), [dialogs and wizards](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Ffirstplugin.htm), [the JFace UI framework](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Ffirstplugin.htm), etc.

As far as I could determine by reading your source code, your prototype builds its own GUI without using Eclipse’s features at all.

**Comment by RomanLangrehr** [comment]
> However, Swing will do for a prototype.

I disagree, too. We don't need a prototype as "mock-up" for the real GUI. We build these prototypes because we want to know how to use a certain framework, here the eclipse-GUI-Features for plugins!

**Comment by m1cm1c** [comment]
Eclipse plugins seem to do this via xml. You can find something in my branch `eclipse-native-gui-prototype`.

**Comment by m1cm1c** [comment]
I've tried them, now, except for JFace which I will look into soon. It was pretty obvious that dialogs and wizards aren't what we want. UI Forms were the most promising of them, especially because [examples like this one showing nice windows](http://www.vogella.com/tutorials/EclipseForms/article.html) can be found. However, they are just views in their own windows. In the version of Eclipse we're using, they even got the view elements (so they are a window with navigation elements and their own tab bar with a single tab in it).

**Comment by m1cm1c** [comment]
Do I really have to look into JFace. It seems horribly outdated, has problems in Luna and Mars (well, its latest release is from July 2013, right after Eclipse Kepler has been released), not a single one of the jars they use in their description even exists anymore, etc. Furthermore, they even want you to start with different templates depending on your operating system which just seems like a bad idea.

**Comment by RomanLangrehr** [comment]
>  It was pretty obvious that dialogs and wizards aren't what we want.

Why are dialogs and wizards not, what we want?

**Comment by m1cm1c** [comment]
>>It was pretty obvious that dialogs and wizards aren't what we want.
>Why are dialogs and wizards not, what we want?

Because we should provide a control GUI, not a dialog (show information) or a wizard (make a few settings, click "next" in-between, then click "finish").

**Comment by RomanLangrehr** [comment]
> a wizard (make a few settings, click "next" in-between, then click "finish").

That sounds exactly like, what we want.
And after finish appears a progress bar dialog with the pause/resume button.

**Comment by jGleitz** [comment]
> That sounds exactly like, what we want. And after finish appears a progress bar dialog with the pause/resume button.

That's what I think, too. Now if there are technical issues with that specific API, we might also look elsewhere. But the fact that there are thousands of uniform Eclipse plugins suggest that there is a proper API to do that. And as far as I can see, the things described in the Eclipse programmers' guide is what the Eclipse team wants us to use. 

Am 24.12.2015 8:18 vorm. schrieb Roman Langrehr <notifications@github.com>:

a wizard (make a few settings, click "next" in-between, then click "finish").

That sounds exactly like, what we want.
And after finish appears a progress bar dialog with the pause/resume button.

**Comment by m1cm1c** [comment]
I don't like this approach, but if you're in favor of it, I'll create a prototype.

**Comment by jGleitz** [comment]
> I don't like this approach, but if you're in favor of it, I'll create a prototype.

Then let us discuss it, that's what GitHub is good for, after all. In the moment, I don't understand what you don't like about the approach (and I don't know any technical details about it either) 

Am 24.12.2015 8:29 vorm. schrieb m1cm1c <notifications@github.com>:

I don't like this approach, but if you're in favor of it, I'll create a prototype.

**Comment by m1cm1c** [comment]
This approach is as follows:
user right-clicks something → wizard opens → user fills out wizard → user clicks on "finish" → wizard closes and dialog opens → user can pause and resume analysis

Pretty linear. But what if the user wants to analyze 5 different modules (but not all there are)? They have to open the wizard for the first component and click through it until the dialog appears. Then they have to open the wizard for the second component, click through it, but don't click finish. They do this for the next 3 components just as they did for the second one. Then they wait for each analysis to finish until they can click "finish" in the wizard of the next one. Have fun coordinating which wizard is which and sitting in front of the computer doing nothing but wait for hours. Even if we tell each wizard to sleep until the previous analysis finishes before the dialog is opened (so the user doesn't have to wait all day but can click "finish" right away instead), there are 5 dialogs open in the end.

If we use a custom-built gui, we can show some kind of batch table. We can even neatly show when a timeout occurred (without opening an unnerving popup every single time) and ask the user what to do about it (but of course still continue the other measurements without user interaction).

**Comment by jGleitz** [comment]
>But what if the user wants to analyze 5 different modules

He selects all five, does a right click and continues with the normal, linear process. Isn't that a whole lot easier than showing a batch table (which from my point of view will not be used much because most users will mainly want to analyse their whole project)? 

>We can even neatly show when a timeout occurred (without opening an unnerving popup every single time) and ask the user what to do about it (but of course still continue the other measurements without user interaction).

What do dialogues lack that we can't show information in them as soon as user interaction is desired?

Am 24.12.2015 8:56 vorm. schrieb m1cm1c <notifications@github.com>:

This approach is as follows:
user right-clicks something → wizard opens → user fills out wizard → user clicks on "finish" → wizard closes and dialog opens → user can pause and resume analysis

Pretty linear. But what if the user wants to analyze 5 different modules (but not all there are)? They have to open the wizard for the first component and click through it until the dialog appears. Then they have to open the wizard for the second component, click through it, but don't click finish. They do this for the next 3 components just as they did for the second one. Then they wait for each analysis to finish until they can click "finish" in the wizard of the next one. Have fun coordinating which wizard is which and sitting in front of the computer doing nothing but wait for hours. Even if we tell each wizard to sleep until the previous analysis finishes before the dialog is opened (so the user doesn't have to wait all day but can click "finish" right away instead), there are 5 dialogs open in the end.

If we use a custom-built gui, we can show some kind of batch table. We can even neatly show when a timeout occurred (without opening an unnerving popup every single time) and ask the user what to do about it (but of course still continue the other measurements without user interaction).

**Comment by m1cm1c** [comment]
Okay, I'll create a prototype.

**Comment by jGleitz** [comment]
This is redeemed by #577
