### ISSUE TITLE
[Checkstyle] Magic Numbers

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#325]
![](http://i.imgur.com/U2ASrEt.png)

I thing the magic numbers thing is getting out of hand. What the `2` means, is very self-explanatory. Plus, it's malfunctioning because in line 68, Checkstyle doesn't display any problems but in line 73 – which does the exact same thing – it does.

**Comment by jGleitz** [comment]
I think this is a good example for why this rule makes perfectly sense. 

I agree that it is obvious what purpose these numbers serve. However, if I (who did not write this code) was to change the number of columns in the code (which by the time has grown considerably bigger), I might have a hard time looking for where I have to make a change. If you'd put these numbers into constant fields having speaking names, I'd find them very fast. 

The "no magic numbers rule" is very important from my point of view, because it prevents developers to hardcore related values instead of expressing them through a common variable. And most of the time, using more, well named variables and fields leads to better readability because they give good hints about what the code does. 

As far as I know (@acBerger might confirm), the `1` is excluded because one might think it's typical to be used. But as one can use the `++` and `--` operators, I think we can remove this exception. 

Am 26.12.2015 9:32 vorm. schrieb m1cm1c <notifications@github.com>:

 

I thing the magic numbers thing is getting out of hand. What the 2 means, is very self-explanatory. Plus, it's malfunctioning because in line 68, Checkstyle doesn't display any problems but in line 73 – which does the exact same thing – it does.
