### ISSUE TITLE
Find Impl-Classes that implement Interfaces

### ISSUE THREAD

**Issue by flyfl** [Beagle-PSE/Beagle#463]
Interfaces without classes that implement those are quite useless.

Interfaces: Measurement Tool, ResultAnalyser, FinalJudge, EvaluableExpression.

**Comment by RomanLangrehr** [comment]
Suggestion: Create a class that implements them ;)

**Comment by flyfl** [comment]
That sounds nice :)
But that belongs into the Diagram, doesn't it?

**Comment by RomanLangrehr** [comment]
Yes, it definitly does!

And if you have an idea how these classes will work, start modelling them. However, I have no idea (at least not in detail).
But we should add some simple classes like "Averaging Final Judge". I think this for example, only needs to implement the interface's methods.

And for the EvalubleExpression: I think there are hundreds of classes implemting them.

**Comment by flyfl** [comment]
Some questions/ideas have arosen so far, thinking about a concrete Impl-Class of `FinalJudge` and `AnalyserTool`.
I don't think we don't need to answer all of these questions right now, but maybe some of them can help for final design decisions (at least it will support the `Implementation phase`)

When I read, what you are talking about, it seems like the Average concept (easiest way to parametrerise the PCM) is taken by a FinalJudge.
But then, what's the task of an AnalyserTool? And how does the Judge his job?

##My ideas to "What's the task of an AnalyserTool?"
- **Average Approach:**
The task of an Average Analyser is, to calculate average evaluable expressions and annotate them on `Measurable SEFF Components`.

- **Genetic Approach:**
I think everything of the logic of the genetic approach belong into the GeneticAnalyser. The FinalJudge has nothing to do with this approach,
unless we will create AnalyserTool depending Judges (if we realise, that a judge that is synchronised to an AnalyserTool works better).

- "**[...] What do you want to say? I know the idea behind average and genetic approach already!"**
I want to state out, that we must recognise the big difference between AnalyserTool and FinalJudge as we don't want to mix up their logic.

##My ideas to "How does the judge his job?"
The judge has a **weighting function**, mapping the tuple (annotated ev. expression, measurement result)
on a real number. This weighting fuction may depend on a specific implementation of a ResultAnalyser or not.
Besides, we have to decide WHEN a jugde feels happy with a concrete result.
I propose that this depends on a **degree of improvement** (how often is this degree updated? Everytime the FinalJudge judges?)
and a defined **period of time**. One could also imagine that there is an interdependency between degree of improvement and period of time.
For example, when the degree of improvement looks "good enough", the influence of period of time may decrease OR the value of period of time is increased.

###Why could the weighting function depend on a concrete AnalyserTool?
**An example:** On the one hand you have a worker, that does his job extremly fast and you get average results in a very short time.
But you know, that his results will not get much better, if you let him work over and over again.
On the other hand you have a worker, that does his job not that fast, and it takes its time to get modest result back from him.
But this worker, in contrast to the other one, will improve, once he found a result, very fast, so you let him work and give him more time.
**Do you want to judge the workers the same way or different?** If you have only one worker, it makes sense. If you have more worker at once, put them together and give them a blackboard to communicate. Then you can judge on the whole team performance. But that would mean, a judge is enough flexible to make such a decision.

**Comment by jGleitz** [comment]
I’ve already thought about some of the points you make myself and think that you are pointing at a **design flaw**.

@RomanLangrehr, @viridispirus, @m1cm1c, @acBerger, I think this is really important and you should follow this. @flyfl found some critical points.

## Some answers to your questions

>  Besides, we have to decide WHEN a jugde feels happy with a concrete result.
> …

I don’t think so. It’s up to the Final Judge to decide this and may vary from judge to judge.

 > Why could the weighting function depend on a concrete AnalyserTool?

Not at all! The Final Judge may only end the analysis, it does not control which analysers run! 
To solve your scenario: The analysers get ask whether they want to contribute. So your first analyser will only contribute once and never again. *They decide that themselves*.

> Do you want to judge the workers the same way or different?

The Final Judge only judges *results*. It cannot judge analysers differently because it only looks at their results (without knowing where they come from.

## My points

### What does a Result Analyser do?
In the moment: Analyse measurement results *or* proposed expressions and propose new expressions.

### What does the Final Judge do?
In the moment: *The same a Result Analyser*. But he always runs last and may end the analysis.

### What *should* the Final Judge do?
As @flyfl says: only look at the results, look for the best one and mark it as `final`. If he thinks the results are not good enough, he can decide not to end the analysis and look for better ones. But he should not be able to contribute new results.

In current design, this would lead to a problem: The genetical tool would become a `Measurement Result Analyser`. But then we can’t assure it runs last. If it runs for example before an interpolation tool, *we’d lose tons of computation time*. Because the genetic approach will get a lot faster with the interpolation results.

But I think there is a solution:

### What *should* the Measurement Result Analyser do?
Only look at Measurement Results and propose expressions for them.

### What *should* the Proposed Expression Analyser do?
This new Analyser should only be run if no Measurement Result Analyser wants to contribute in the moment. It should only look at the proposed expressions and propose new expressions.


## Conclusion
In this design, the genetic tool would be a Proposed Expression Analyser. As the Final Judge will likely the same (or at least a similar) fitness function as the Genetic Analyser, its results will always be accepted. But because *they are the best* and not because its hardcoded.

What do you think about this refined approach? I want to point out that it fits very well to the different abstraction layers of the Blackboard Pattern:

Code sections < Measurement Results < Proposed Expressions < Final Expression

**Comment by flyfl** [comment]
I agree to each point you carved out. The discrimination between Measurement Result Analyser and Proposed Expression Analyser is a good idea. It just bothers me, that the FinalJudge and the GeneticTool will get the same fitness function, but I don't have a better idea for that.

**Comment by jGleitz** [comment]
We defined the first set of implementation classes. The design is finished and there are currently no problems with it. As far as I’m concerned, this topic is finished.
