### ISSUE TITLE
Drop the Final Judge Blackboard View

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#484]
I made up my mind: We neither have to protect us from nor communicate our API to our own code. I think it serves no use anymore.

**Comment by jGleitz** [comment]
The same arguments can be applied to the Measurement Controller.

**Comment by acBerger** [comment]
I agree.

**Comment by RomanLangrehr** [comment]
I think we definitly have to protect us from our own code! (Otherwise there should nothing be "private", but everything at least "default").
That the final judge has full acces to the blackboard is okay, because his view would have all methods anyway. BUT: The measurement controller should not have acces to all methods! There should be a view for him!

**Comment by flyfl** [comment]
>I think we definitly have to protect us from our own code!

Yes. We have divided functionality and therefore the views make sense. We get a problem if we divide the implementation and some tools are created rival and have full access to the blackboard.
