### ISSUE TITLE
Finalise GUI

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#579]

**Comment by jGleitz** [comment]
As this was scheduled for yesterday: @m1cm1c, can you give us an overview of your progress?

**Comment by m1cm1c** [comment]
The GUI should be finished but I can't test it right now because `BeagleController` is needed to connect the GUI to Beagle Core but somehow went missing. (I wrote the code blindly without this class, so I can't let it run.) @RomanLangrehr needs to write a little bit of Javadoc in his classes and #604 needs to get done so no Checkstyle errors occur any more. Then a pull request from https://github.com/Beagle-PSE/Beagle/tree/ip-030-gui to master can be opened.

**Comment by m1cm1c** [comment]
I found the missing class. Someone moved it to the wrong project. However, they didn't change the package so Javadoc still showed the correct package which was why I wasn't able to locate it at first.

**Comment by m1cm1c** [comment]
I found the missing class. Someone moved it to the wrong project. However, they didn't change the package so Javadoc still showed the correct package which was why I wasn't able to locate it at first.

**Comment by jGleitz** [comment]
> Someone moved it to the wrong project.

In which project did you find it? I guess it belongs in Core.

**Comment by m1cm1c** [comment]
Someone moved it to the GUI project. It now is in Core, again.
