### ISSUE TITLE
[IP #137] Implement Final Judge

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#612]
Implement Final Judge.

Depends on IP#060 (Blackboard) ( #573 ) and IP#120 (Measurement Results) ( #609 )
(Not depending on #160 (Fitness Function), because only method
stubs are needed here.)

**Comment by jGleitz** [comment]
I’d like to test this.

**Comment by jGleitz** [comment]
@m1cm1c could you please upload your progress (in a branch named `ip-137-final-judge`, the `#` is breaking stuff)?

I need at least the correct API to test against, because there’s only the interface `FinalJudge` in `master` at the moment.

**Comment by m1cm1c** [comment]
Done.

**Comment by jGleitz** [comment]
I just realised that testing this also depends on #598

**Comment by jGleitz** [comment]
@m1cm1c I’m in the progress of testing this. I am a little stuck because the test I write need far to long to finish ad I need to think of faster ways.

Nevertheless, your implementation seems to have issues with no proposed expressions or something like that. See the `doesNotEndWhileThereIsImprovement` test.
