### ISSUE TITLE
Modifying & Analysing Evaluable Expressions

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#615]
#608 

In our Evaluable Expression Stubs we have for some evaluable expressions only setters and for others only a constructor. We need to decide how we want to set the inner expressions.
If we decide on only using a constructor we will not have the possibility to change them again (could be wanted when trying to create a similar evaluable expression to propose). On the other hand we then cannot change the values by mistake.

**Comment by m1cm1c** [comment]
Flyweight and setters are incompatible. 

On January 19, 2016 6:03:53 PM GMT+01:00, acBerger <notifications@github.com> wrote:
>#608 
>
>In our Evaluable Expression Stubs we have for some evaluable
>expressions only setters and for others only a constructor. We need to
>decide how we want to set the inner expressions.
>If we decide on only using a constructor we will not have the
>possibility to change them again (could be wanted when trying to create
>a similar evaluable expression to propose). On the other hand we then
>cannot change the values by mistake.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Beagle-PSE/Beagle/issues/615

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jGleitz** [comment]
> Flyweight and setters are incompatible.

That’s correct, although we could easily make an exception for Constants.

I think EvaExes *must* be immutable, because otherwise, people could change the final expression (not necessarily on purpose). 

But: If they are immutable, how can we create copies with only little modification? Say I have a huge expression and know that if I changed one constant, it’d be better. How do I create the new expression with the changed constant?

**Comment by RomanLangrehr** [comment]
> I think EvaExes *must* be immutable, because otherwise, people could change the final expression (not necessarily on purpose).

They could change not only the final expressions, but the whole blackboard content.

> But: If they are immutable, how can we create copies with only little modification? Say I have a huge expression and know that if I changed one constant, it’d be better. How do I create the new expression with the changed constant?

What about an copy-on-write approach? (I didn't found a more concrete, working solution yet.)

**Comment by jGleitz** [comment]
> What about an copy-on-write approach? (I didn't found a more concrete, working solution yet.)

Yeah, something like that. So instead of setters, we would have methods that return a new EvaEx with one inner Expression replaced, right?

**Comment by RomanLangrehr** [comment]
> Yeah, something like that. So instead of setters, we would have methods that return a new EvaEx with one inner Expression replaced, right?

No, I think that's a bad solution, becaus you have to rebuild all "outer" EvaExs.

**Comment by jGleitz** [comment]
> No, I think that's a bad solution, becaus you have to rebuild all "outer" EvaExs.

Yes, of course you have. You have to recursively go up and do exactly that. But I don’t see a better approach.

**Comment by RomanLangrehr** [comment]
> Yes, of course you have. You have to recursively go up and do exactly that. But I don’t see a better approach.

What about a visitor, which gets the EvaEx to replace and does the "go up" for you?

**Comment by jGleitz** [comment]
> What about a visitor, which gets the EvaEx to replace and does the "go up" for you?

I thought about that too, but how do you explicitly formulate the replacement you want to make? Note that one instance of an EvaEx may appear arbitrary often in an EvaEx.

**Comment by jGleitz** [comment]
I think I found a way to tackle this elegantly. 

If @RomanLangrehr approves, I’ll try to implement a solution today.

**Comment by RomanLangrehr** [comment]
Of course I approve.

**Comment by jGleitz** [comment]
I think I’ve created a decent solution for this. I pushed it to `evaex-visitors` in our repo.

It contains the following classes:

### RecursiveEvaluableExpressionVisitor
Does a depth-first traversal of the expression tree and offers a lot of hooks for that.

### AbstractEvaluableExpressionVisitor
Convenience class that allows the implementor to only override certain `visit` methods and have a `visitOther` method for other cases.

### ModifyingEvaluableExpressionVisitor
Traverses the expression tree with the same hooks as `RecursiveEvaluableExpressionVisitor`. However, implementors can call `replaceCurrentExpressionWith(EvaluableExpression)` at any point in the traversal. This will replace the currently visited expression with a new one and continue traversal in the new expression. The class will take care of replacing parent expressions accordingly.

The class does the heavy lifting of the replacements. For an implementor, modifying expressions gets very easy, because he only has to define what he wants to replace with what.

### EvaluableExpressionSimplifier
Prove of concept for `ModifyingEvaluableExpressionVisitor`. Is meant to simplify expressions. In the moment, it only handles additions and can do things like `((x + 4.0 + (y + z + (3.0 + 3.0 + 4.0))) + (a - (5.0 + 4.0)))` → `(x + 5.0 + y + z + a)`

**Comment by jGleitz** [comment]
I’m happy to hear your thoughts on this API.

**Comment by flyfl** [comment]
I can't find those classes. I checked out `ip#110-eval` as there is no `evaex-visitors` branch.

**Comment by jGleitz** [comment]
> there is no `evaex-visitors` branch.

I’m sorry, I pushed it to my repo. Now it’s there.

**Comment by RomanLangrehr** [comment]
lgtm.
